server:
  port: 8089

spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url: 'jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1'
    password: ''
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: 'true'
      path: /h2-console